POST 

const url = "localhost:";

POST {url}/official-student
{
    "name" : "",
    "phone" : "",
    "contact_page_day":"",
    "is_under_care" : 1,
    "DOB" : "",
    "occupation": "",
    "address":"",
    "student_id_list" :[
        "ObjectIdabciaosjddw948092184",
        "ObjectIdabciaosjddw948092184"
    ],
    "class_id" : "",
    "discount_code":"",
    "remain
    
    //optional
    "parent_info" : {
        "name": "",
        "role": "",
        "phone": "",
        "email":"",
        "facebook":""
    },
 
}

