POST 

const url = "localhost:";

POST {url}/potential-student
{
    "full_name" : "pham nguyen tan trung",
    "phone_number" : "01231240128",
    
    "entry_test_datetime": [
        {
            "date": "12/25/2021",
            "day_session": "morning",
            "time" : "79",
            "skill" : "listening"
        },
        {
            "day_session":"evening",
            "date": "7/12/2021 ",
            "time" : "1921",
            "skill" : "reading"
        }
    ] ,
    
    "final_test_datetime": [
         {
            "date": "12/25/2021",
            "day_session": "mor",
            "time" : "79",
            "skill" : "listening"
        },
        {
            "day_session":"eve",
            "date": "7/12/2021 ",
            "time" : "1921",
            "skill" : "reading"
        },
        {
            "day_session":"eve",
            "date": "7/12/2021 ",
            "time" : "1921",
            "skill" : "speaking"
        }
    ] ,
    
    "contact_page_date":"12/06/2010",
    "dob" : "06/05/1995",
    "occupation": "student",

    "friend_student_id_list" :[
        {"student_id": "ObjectIdabciaosjddw948092184"},
        {"student_id": "ObjectIdabciaosjddw948092184"}
    ],

    "parent_info" : {
        "name": "fwea",
        "role": "fwa",
        "phone": "wfaw",
        "email":"fewafew",
        "facebook":"fewafew"
    },

    "free_days_list" :[
        {
            "day_session": "mor",
            "weekdays_and_time":[
                {
                    "day" : "mon",
                    "time": "79"
                },
                {
                    "day" : "wed",
                    "time": "810"
                },
                {
                    "day" : "fri",
                    "time": "810"
                }
            ]
        },
        {
            "day_session": "aft",
            "weekdays_and_time":[
                {
                    "day" : "mon",
                    "time": "1315"
                },
                {
                    "day" : "wed",
                    "time": "1517"
                },
                {
                    "day" : "fri",
                    "time": "1921"
                }
            ]
        }
    ],
    "is_returning_student": 1,

    "previous_class_code_enrolled": [
        { "class_code": "fewafoawei"},
        { "class_code": "fewafoawei"}
    ],

    "is_reminded_before_entry_test_date" : 1,
    "is_reminded_before_final_test_date" : 1,
    "is_attend_entry_test_date" : 1,
    "is_attend_final_test_date" : 0,

    "entry_test_result": {
        "speaking" : 6.5,
        "listening" : 6.5,
        "writing" : 6.5,
        "reading" : 6.5,
        //0.25 -> 0.5
        //0.75 -> 
        7.8321938 -> 8.0
        
        "overall_band_score": 6.5
     },

      "final_test_result": {
        "speaking" : 6.5,
        "listening" : 6.5,
        "writing" : 6.5,
        "reading" : 6.5,
        "overall_band_score": 6.5
    },
    
    "current_class_code_enrolled": "MA45IELTS", 

    "applied_offer":[
        {
         "offer_description" : "5% giảm sách",
         "offer_code" : "001"
        }
    ],

    "notes" : "this is good" 
}