POST url HTTP/1.1
const url = "localhost:8080/label
[
    {
        level_description: "PRE-IELTS 4.5-5.5"
    },
]

GET url HTTP/1.1
[
    {
        label_name: "A",
        description: [
            {
                day: "Monday",
                time range: "7:00 to 9:00"
            },
            {
                day: "Thursday",
                time range: "7:00 to 9:00"
            }
        ]
    }
]

DELETE url HTTP/1.1
//delete all ?? delete one record
[
    {
        label_name: "A",
     description: [
            {
                day: "Monday",
                time range: "7:00 to 9:00"
            },
            {
                day: "Thursday",
                time range: "7:00 to 9:00"
            }
        ]
    },
    {
        label_name: "A",
     description: [
            {
                day: "Monday",
                time range: "7:00 to 9:00"
            },
            {
                day: "Thursday",
                time range: "7:00 to 9:00"
            }
        ]
    }
]

PUT url HTTP/1.1
[
     label_name: "A",
     description: [
            {
                day: "Monday",
                time range: "7:00 to 9:00"
            },
            {
                day: "Thursday",
                time range: "7:00 to 9:00"
            }
        ]
]

//update 1 phan 
PATCH url HTTP/1.1
[
    {
        userId: "ObjectId"
        role: "",
    }
]