const URL = "localhost:";

POST url HTTP/1.1
{
    "class_name": "rachua",
    "class_label": "A",
    "class_level": "45",
    "slots": 19,
    "total_sessions": 33,
    "date_start":"06/05/1995",
    "is_active": 0,
    "tuition_fee":2000000,
    "class_session": [
            {
                "day_session" : "eve",
                "day": "mon",
                "time_range": "1921",
                "skills" :["listening", "speaking"]
            },
            {
                "day_session" : "eve",
                "day": "wed",
                "time_range": "1921",
                "skills": ["reading","writing"]
            }
      ],
    "student_list" : [
         "foeiwafoibwea",
         "foeiwafoibwea"
    ],
   "class_notes": "this is a new class"
}

UPDATE url HTTP/1.1
