const URL = "localhost:";

POST url HTTP/1.1
{
    "class_name": "pre ielts",
    "class_label": "A",
    "class_level": "45",
    "slots": 19,
    "total_sessions": 33,
    "date_start":"06/05/1995",
    "is_active": 1,
    "tuition_fee":2000000,
    "class_session": [
            {
                "day": "Monday",
                "time_range": "7:00 - 9:00"
            },
            {
                "day": "Thursday",
                "time_range": "7:00 - 9:00"
            }
      ],
    "student_list" : [
         {
            "student_id" : "foeiwafoibwea",
            "dob" :"22/02/2002",
            "contact_info": "111/222 ABC street",
            "test_date" : "02/02/2000",
            "initial_test_result" : "6.5",
            "class_level_enrolled": "abfawef291239",
            "discount_code" : "5%",
            "amount_paid" : 2000000,
            "amount_remaining" : 0,
            "student_notes" : "da lien he phu huynh"
        }
    ],
   "class_notes": "this is a new class"
}

UPDATE url HTTP/1.1
